name: Publish to CurseForge
on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Package and Upload
        uses: BigWigsMods/packager@v2
        with:
          args: -p 1404866
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
